-- CONSULTA QUE TRAGA A SOMA DE VENDA, QUANTIDADE DE DIAS POSITIVADOS, QUANTIDADE DE CLIENTES E
-- QUANTIDADE TOTAL VENDIDA DOS PRODUTOS DA MARCA VERSOTOOLS QUE TENHAM UM VALOR DE VENDA
-- MAIOR QUE R$ 2.000,00;

--Checklist
--A SOMA DE VENDA ok
--QUANTIDADE DE DIAS POSITIVADOS ok
--QUANTIDADE DE CLIENTES ok
--QUANTIDADE TOTAL VENDIDA DOS PRODUTOS DA MARCA VERSOTOOLS QUE TENHAM UM VALOR DE VENDA MAIOR QUE R$ 2.000,00; ok i guess?

  SELECT a.MARCA                        AS MARCA,
         b.CODPROD                      AS CODIGO_PRODUTO,
         b.DESCRICAO                    AS DESCRICAO,
         TRUNC(SUM(c.QT) / COUNT(DISTINCT c.PVENDA), 2) AS MEDIA_VENDAS,
         TRUNC(SUM(d.VLTOTAL), 2)        AS VL_TOTAL_VENDIDO,
         COUNT(DISTINCT d.CODCLI)       AS QTD_CLIENTES,
         SUM(c.QT)                      AS QT_TOTAL_VENDIDAS
    FROM PCMARCA a
    JOIN PCPRODUT b
      ON b.CODMARCA = a.CODMARCA 
    JOIN PCPEDI c
      ON c.CODPROD = b.CODPROD
    JOIN PCPEDC d
      ON c.NUMPED = d.NUMPED
   WHERE a.CODMARCA = 66
     AND d.POSICAO = 'F'
GROUP BY a.MARCA,
         b.CODPROD,
         DESCRICAO,
         c.PVENDA 
HAVING SUM(d.VLTOTAL) > 2000