--CONSULTA QUE TRAGA A VENDA TOTAL, TOTAL DE CLIENTES POSITIVADOS, MEDIA DE VALOR POR
--REPRESENTANTE E MEDIA DE DIAS POR REPRESENTANTE DE TODOS OS SUPERVISORES COM VENDA MENOR
--QUE R$ 10.000,00.

--Checklist
--venda total OK
--total de clientes positivados ok
--media de valor por representa ok 
--media de dias por representante de todos os supervisores cm venda menor que 10.000


  SELECT a.CODUSUR,
         a.CODSUPERVISOR,
   TRUNC(SUM(b.QT * b.PVENDA), 2) AS VENDA_TOTAL,
   COUNT(DISTINCT b.CODCLI)AS TOTAL_CLI_POSI,
   TRUNC(SUM(b.PVENDA) / COUNT(DISTINCT a.CODUSUR), 2) AS VALOR_MEDIO_VENDEDOR,
   COUNT(d.DATA) / COUNT(DISTINCT a.CODUSUR) AS MEDIA_DE_DIAS
    FROM PCUSUARI a
    JOIN PCPEDI b
      ON b.CODUSUR = a.CODUSUR
    JOIN PCPEDC d
      ON b.NUMPED  = d.NUMPED 
    JOIN PCSUPERV e
      ON e.CODSUPERVISOR = a.CODSUPERVISOR 
   WHERE d.POSICAO = 'F'
GROUP BY a.CODUSUR,
		 a.CODSUPERVISOR
  HAVING SUM(b.QT * b.PVENDA) < 10000