-- CONSULTA QUE TRAGA A SOMA DE VENDA, QUANTIDADE DE DIAS POSITIVADOS, QUANTIDADE DE CLIENTES E
-- QUANTIDADE TOTAL VENDIDA DOS PRODUTOS DA MARCA VERSOTOOLS QUE TENHAM UM VALOR DE VENDA
-- MAIOR QUE R$ 2.000,00;

--Checklist
--A SOMA DE VENDA ok
--QUANTIDADE DE DIAS POSITIVADOS ok
--QUANTIDADE DE CLIENTES ok
--QUANTIDADE TOTAL VENDIDA DOS PRODUTOS DA MARCA VERSOTOOLS QUE TENHAM UM VALOR DE VENDA MAIOR QUE R$ 2.000,00; ok

  SELECT PCMARCA.MARCA                                            AS MARCA,
         PCPRODUT.CODPROD                                         AS CODIGO_PRODUTO,
         PCPRODUT.DESCRICAO                                       AS DESCRICAO,
         TRUNC(SUM(PCPEDI.QT) / COUNT(DISTINCT PCPEDC.NUMPED), 2) AS MEDIA_VENDAS,
         TRUNC(SUM(PCPEDI.QT * PCPEDI.PVENDA), 2)                 AS VL_TOTAL_VENDIDO,
         COUNT(DISTINCT PCPEDC.CODCLI)                            AS QTD_CLIENTES,
         SUM(PCPEDI.QT)                                           AS QT_TOTAL_VENDIDAS
    FROM PCMARCA 
    JOIN PCPRODUT 
      ON PCPRODUT.CODMARCA = PCMARCA.CODMARCA 
    JOIN PCPEDI 
      ON PCPEDI.CODPROD = PCPRODUT.CODPROD
    JOIN PCPEDC 
      ON PCPEDI.NUMPED = PCPEDC.NUMPED
   WHERE PCMARCA.CODMARCA = 66
     AND PCPEDC.POSICAO = 'F'
GROUP BY PCMARCA.MARCA,
         PCPRODUT.CODPROD,
         DESCRICAO,
         PCPEDI.PVENDA 
HAVING SUM(PCPEDC.VLTOTAL) > 2000