--CONSULTA QUE TRAGA A VENDA TOTAL, TOTAL DE CLIENTES POSITIVADOS, MEDIA DE VALOR POR
--REPRESENTANTE E MEDIA DE DIAS POR REPRESENTANTE DE TODOS OS SUPERVISORES COM VENDA MENOR
--QUE R$ 10.000,00.

--Checklist
--venda total OK
--total de clientes positivados ok
--media de valor por representa ok 
--media de dias por representante de todos os supervisores cm venda menor que 10.000

  SELECT PCUSUARI.CODUSUR                              AS CODIGO_DE_USUARIO,
         PCUSUARI.CODSUPERVISOR                        AS CODIGO_DE_SUPERVISOR,
   TRUNC(SUM(PCPEDI.QT * PCPEDI.PVENDA), 2)            AS VENDA_TOTAL,
   COUNT(DISTINCT PCPEDI.CODCLI)                       AS TOTAL_CLIENTES_POSITIVADOS,
   TRUNC(SUM(PCPEDI.PVENDA * PCPEDI.QT), 2)            AS VALOR_MEDIO_VENDEDOR,
   COUNT(DISTINCT PCPEDC.DATA)                         AS MEDIA_DE_DIAS
    FROM PCUSUARI 
    JOIN PCPEDI 
      ON PCPEDI.CODUSUR = PCUSUARI.CODUSUR
    JOIN PCPEDC 
      ON PCPEDI.NUMPED  = PCPEDC.NUMPED 
    JOIN PCSUPERV
      ON PCSUPERV.CODSUPERVISOR = PCUSUARI.CODSUPERVISOR 
   WHERE PCPEDC.POSICAO = 'F'
GROUP BY PCUSUARI.CODUSUR,
		     PCUSUARI.CODSUPERVISOR
  HAVING SUM(PCPEDI.QT * PCPEDI.PVENDA) < 10000