 -- CONSULTA QUE TRAGA SOMENTE OS PRODUTOS QUE POSSUEM MARCA CADASTRADA. APRESENTANDO, PRODUTO E A DESCRIÇÃO DA MARCA, EM ORDEM ALFABÉTICA;
  
  SELECT PCMARCA.MARCA AS DESCRIÇÃO_DA_MARCA,
         PCPRODUT.*
    FROM PCPRODUT 
    JOIN PCMARCA  
      ON PCPRODUT.CODMARCA = PCMARCA.CODMARCA
ORDER BY PCPRODUT.DESCRICAO ASC;

-- OUTRA FORMA DE FAZER A MESMA CONSULTA É UTILIZANDO ALCUNHA(ALIAS) PARA O NOME DAS TABELAS

  SELECT b.MARCA AS DESCRIÇÃO_DA_MARCA,
         a.*
    FROM PCPRODUT a
    JOIN PCMARCA  b
      ON a.CODMARCA = b.CODMARCA
ORDER BY a.DESCRICAO ASC;