-- CONSULTA QUE TRAGA TODOS OS PRODUTOS E A DESCRIÇÃO DA SUA SEÇÃO (MESMO SE NÃO HOUVER), ORDENADO POR CÓDIGO DE PRODUTO DECRESCENTE;
   
   SELECT PCPRODUT.*,
   	    PCSECAO.DESCRICAO AS SECAO
     FROM PCPRODUT 
LEFT JOIN PCSECAO  
       ON PCPRODUT.CODSEC = PCSECAO.CODSEC
 ORDER BY PCPRODUT.CODPROD DESC;
   

 -- OUTRA FORMA DE FAZER A MESMA CONSULTA É UTILIZANDO ALCUNHA(ALIAS) PARA O NOME DAS TABELAS
   
   SELECT a.*,
   	    b.DESCRICAO AS SECAO
     FROM PCPRODUT a
LEFT JOIN PCSECAO  b 
       ON a.CODSEC = b.CODSEC
 ORDER BY a.CODPROD DESC;