-- CONSULTA QUE TRAGA SOMENTE OS REPRESENTANTES QUE POSSUEM SUPERVISOR VINCULADO NA TABELA DE SUPERVISORES, POR ORDEM ALFABÉTICA;

  SELECT PCUSUARI.NOME AS REPRESENTANTES,
    FROM PCUSUARI
    JOIN PCSUPERV 
      ON PCUSUARI.CODSUPERVISOR = PCSUPERV.CODSUPERVISOR
ORDER BY NOME ASC;

-- SE FOR NECESSARIO APARECER TODOS OS CAMPOS:

  SELECT *
    FROM PCUSUARI
    JOIN PCSUPERV 
      ON PCUSUARI.CODSUPERVISOR = PCSUPERV.CODSUPERVISOR
ORDER BY NOME ASC;


-- OUTRA FORMA DE FAZER A MESMA CONSULTA É UTILIZANDO ALCUNHA(ALIAS) PARA O NOME DAS TABELAS
  
  SELECT a.NOME AS REPRESENTANTES
    FROM PCUSUARI a
    JOIN PCSUPERV b
      ON a.CODSUPERVISOR = b.CODSUPERVISOR
ORDER BY REPRESENTANTES ASC;

-- EXTRA: 
-- A FIM DE TRAZER TODOS OS REPRESENTANTES QUE NÃO POSSUEM SUPERVISOR VINCULADO, PODEMOS UTILIZAR O LEFT JOIN E O IS NULL PARA BUSCARMOS DE FORMA AINDA MAIS MANUAL
-- A DIFERENÇA ENTRE OS DOIS CONJUNTOS DE DADOS, OU SEJA, OS REPRESENTANTES QUE POSSUEM SUPERVISOR VINCULADO E OS QUE NÃO POSSUEM.

   SELECT a.NOME AS REPRESENTANTES, 
          a.CODSUPERVISOR AS CODIGO_DO_SUPERVISOR
     FROM PCUSUARI a
LEFT JOIN PCSUPERV b 
       ON a.CODSUPERVISOR = b.CODSUPERVISOR
    WHERE b.CODSUPERVISOR IS NULL;

-- NESSE CASO OS REPRESENTANTES:
-- JOSE FLORES BETIM COM CODIGO DE SUPERVISOR 15
-- IVO LEMBECK COM CODIGO DE SUPERVISOR 2.
-- NÃO POSSUEM SUPERVISOR VINCULADO, PODENDO TER COMO CONSIDERAÇÃO EM UM CASO REAL UM ERRO DE CADASTRO JÁ QUE O PADRÃO DE CODIGO TENDE A SER 1,0XX.